import {
  IsNotEmpty,
  IsString,
  IsNumber,
  Min,
  Max,
  IsUUID,
  Matches,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger'; // If you use Swagger

export class CreateVoiceMessageDto {
  @ApiProperty({
    description: 'ID of the conversation this voice message belongs to',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  // @IsUUID()
  @IsString()
  @IsNotEmpty()
  conversationId: string;

  @ApiProperty({
    description: 'Duration of the voice message in seconds',
    example: 15.5,
  })
  @IsNumber()
  @Min(0.1) // Assuming a minimum duration
  @Max(300) // 5 minutes max
  duration: number;

  @ApiProperty({
    description: 'MIME type of the voice file',
    example: 'audio/webm',
  })
  @IsString()
  @IsNotEmpty()
  // @Matches(/^(audio\/(mpeg|ogg|wav|webm|aac|mp3|mp4|x-m4a|caf))$/i)
  mimeType: string;

  // The actual file will be handled by Multer (FileInterceptor)
  // The filePath will be generated by the service after storing the file.
}
