export const EVENTS = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CONNECT_ERROR: "connect_error",
  IDENTIFICATION_CONFIRMED: "identification-confirmed",
  ROOM_JOINED: "room-joined",
  ROOM_LEFT: "room-left",
  MESSAGE: "message",
  ROOM_HISTORY: "room-history",
  NEW_MESSAGE: "new-message",
  CLEAR_MESSAGES: "clear-messages",
  ERROR: "error",
  SEND_MESSAGE: "send-message",
  JOIN_ROOM: "join-room",
};
